[base]
command_prefix = ['?', '!']
default_prefix = '?'
ignored_prefixes = ['!']
key = ''
admin_ids = [0]  # first ID is used for mention in case of false verification
guild_id = 0

mod_role = 461550034668748800
submod_role = 591372495936815114
helper_role = 461550323727859712

[verification]
role = ''
role_id = 591349196267716608
host_id = 603673568051462144

[email]
name = 'toasterrubbergod@gmail.com'
addr = 'toasterrubbergod@gmail.com'
smtp_server = 'smtp.gmail.com'
smtp_port = 465
pass = ''

[database]
db_string = "postgresql://postgres:postgres@db:5432/postgres"

[cogs]
extensions = ['karma', 'meme', 'memerepost', 'random', 'verify', 'fitwide', 'autopin',
    'help', 'review', 'vote', 'week', 'roles', 'error', 'absolvent', 'gif', 'reactions',
    'streamlinks', 'bookmark', 'latex', 'info', 'fun', 'moderation', 'message',
    'timeout', 'forum', 'report', 'contestvote']

[config]
static = ['config_static', 'toml_dict', 'key', 'weather_token', 'db_string']

[random]
enable_room_check = false

[karma]
ban_role_id = -1
#                        add-roles         back-to-school
banned_channels = [591384273051975683, 622202824377237504]
grillbot_leaderboard_size = 50

[vote]
minimum = 20
minutes = 2

[contest_vote]
channel = 0
weight_1 = 2
weight_2 = 1.5
weight_3 = 1

[autopin]
count = 20
#                       skolni-info          server-info
banned_channels = [491277786489683979, 489461089432633346]
banned_users = []
warning_cooldown = 5 # in minutes

[channels]
log_channel = 531058805233156096
bot_dev_channel = 597009137905303552
vote_room = 461544375105749003
bot_room = 461549842896781312
mod_room = 505679727936143361
submod_helper_room = 1023669101744357377
report_channel = 1120635712950251551

allowed_channels = [
        'bot_room',
        'bot_dev_channel'
]

[role]
#           add-roles           back-to-school      summertime-madness
channels = [591384273051975683, 622202824377237504, 623290691774316574]

[meme_repost]
meme_room = 0
meme_repost_room = 0
repost_threshold = 50
image_extensions = ["png", "jpg", "jpeg", "gif"]

[meme]
uhoh_string = 'uh oh'
upgraded_pocitani_thread_id = 1082751957288100042
upgraded_pocitani_start_num = 1
hug_emojis = ["<:peepoHug:600435649786544151>",
    "<:peepoHugger:602052621007585280>",
    "<:huggers:602823825880514561>", "(っ˘̩╭╮˘̩)っ", "(っ´▽｀)っ",
    "╰(*´︶`*)╯", "(つ≧▽≦)つ", "(づ￣ ³￣)づ", "(づ｡◕‿‿◕｡)づ",
    "(づ￣ ³￣)づ", "(っ˘̩╭╮˘̩)っ", "⁽₍੭ ՞̑◞ළ̫̉◟՞̑₎⁾੭",
    "(੭ु｡╹▿╹｡)੭ु⁾⁾", "(*´σЗ`)σ", "(っ´▽｀)っ", "(っ´∀｀)っ",
    "c⌒っ╹v╹ )っ", "(σ･з･)σ", "(੭ु´･ω･`)੭ु⁾⁾", "(oﾟ▽ﾟ)o",
    "༼つ ் ▽ ் ༽つ", "༼つ . •́ _ʖ •̀ . ༽つ", "╏つ ͜ಠ ‸ ͜ಠ ╏つ",
    "༼ つ ̥◕͙_̙◕͖ ͓༽つ", "༼ つ ◕o◕ ༽つ", "༼ つ ͡ ͡° ͜ ʖ ͡ ͡° ༽つ",
    "(っಠ‿ಠ)っ", "༼ つ ◕_◕ ༽つ", "ʕっ•ᴥ•ʔっ", "", "༼ つ ▀̿_▀̿ ༽つ",
    "ʕ ⊃･ ◡ ･ ʔ⊃", "╏つ” ⊡ 〜 ⊡ ” ╏つ", "(⊃｡•́‿•̀｡)⊃", "(っ⇀⑃↼)っ",
    "(.づ◡﹏◡)づ.", "(.づσ▿σ)づ.", "(っ⇀`皿′↼)っ",
    "(.づ▣ ͜ʖ▣)づ.", "(つ ͡° ͜ʖ ͡°)つ", "(⊃ • ʖ̫ • )⊃",
    "（っ・∀・）っ", "(つ´∀｀)つ", "(っ*´∀｀*)っ", "(つ▀¯▀)つ",
    "(つ◉益◉)つ", " ^_^ )>", "───::≡≡ΣΣ((( つºل͜º)つ",
    "─:≡Σ((( つ◕ل͜◕)つ", "─:≡Σ((( つ ◕o◕ )つ",
    "～～～～(/￣ｰ(･･｡)/", "───::≡≡ΣΣ(づ￣ ³￣)づ",
    "─:≡Σʕっ•ᴥ•ʔっ", "───::≡≡ΣΣ(> ^_^ )>", "─:≡Σ༼ つ ▀̿_▀̿ ༽つ",
    "───::≡≡ΣΣ(っ´▽｀)っ", "───::≡≡ΣΣ(っ´∀｀)っ", "～～(つˆДˆ)つﾉ>｡☆)ﾉ"]

[review]
#                  MUNI                Host
forbidden_roles = [600047283509264384, 603673568051462144]
bit_id = 7886
mit_id_start = 14967
mit_id_end = 14983
mit_id_rnd = [15220]

[grillbot]
#      Production,         Development
ids = [902678773307174943, 599119578811072523]
api_url = "https://grillbot.eu/api"
api_supported_methods = ["Help", "AutoPin"]
api_key = ""
karma_sync_interval = 60 # Update interval in minutes for automatic sync karma.

[weather]
token = "678a5932f6dd92ac668b20e9f89c0318"

[warden]
duplicate_limit = 5
#                           #memes              #aww
deduplication_channels = [461548323116154880, 543083844736253964]
repost_ignore_users = [0]

[week]
starting_week = 5

[absolvent]
bc_role_id = 0
ing_role_id = 0

[emote]
loading="<a:loading:814969399442014259>"

[util]
ios_looptime_minutes=120
ios_channel_id=534431057001316362

[exams]
page_size = 6
paginator_duration = 60
term_channels = ["1bit-terminy", "2bit-terminy", "3bit-terminy", "mit-terminy"]
terms_update_interval = 0.5 # Update interval in days for automatic updating
subscribe_default_guild = true

[icons]
icon_roles = [0,1]
role_prefix = "ico-"
ui_cooldown = 10.0
[icons.rule.0]
allow=[] # prevent anyone from self-assigning this role
[icons.rule.1]
deny=[461550034668748800, 140547421733126145] # prevent mods and the user arcasCZ from self-assigning this icon via the UI.

[timeout_wars]
reaction_count = 10
log_channel = 1091275431866544148
immunity_time = 15
timeout_time = 10
chance_all_mute = 5
chance_random_mute = 25

[forum]
tags = ["prodáno/uzavřeno"]
autoclose_forums = [1064946755231297536]
